### ISSUE TITLE
Thanks, and checking to see if you have a few missing states

### ISSUE THREAD

**Issue by dwmmclaughlin** [justinelliotmeyers/official_india_2011_village_boundary_polygons#1]
Hey,

Thanks for posting these! I am in the process of mapping ids to the missing villages and I wanted to check and see if you had the other shapefiles for completeness.

Do you by chance have the following states which are not included in this GitHub repo?

villages_02 (Himachal Pradesh)
villages_04 (Chandigarh)
villages_11 (Sikkim)
villages_12 (Arunachal Pradesh)
villages_13 (Nagaland)
villages_14 (Manipur)
villages_15 (Mizoram)
villages_17 (Meghalaya)

Thanks so much, and I hope to hear from you soon.

Best,

Dave

**Comment by justinelliotmeyers** [comment]
Dave, this is the full dataset from the source. I can go back and see if something was missing from the upload, but think I checked that twice post upload.  Since I uploaded this, I found two other full India village datasets, but haven't looked at them, just downloaded. What IDs are you mapping to the data?  Thanks! Justin

**Comment by dwmmclaughlin** [comment]
Hi Justin,

My plan was to map the Census state, district, and sub-district codes, and then to use a fuzzy merge based on village names to get village codes mapped to the unknown villages.  The codes I would be mapping would be from the to the universe of villages ([here](http://www.censusindia.gov.in/2011census/Listofvillagesandtowns.aspx)).

If you have a complete Indian village dataset (where all villages have state, district, sub-district, and village census codes) I would be very interested in using it.  I am an academic working on a project looking at the impact of a large-scale project on air quality.

Thanks so much for the quick response!

Best,

Dave

**Comment by justinelliotmeyers** [comment]
Email me and we can chat

**Comment by dwmmclaughlin** [comment]
Hi Justin,

I couldn't find your email (after a short search), but you can email me at d.wm.mclaughlin [{at}] berkeley.edu (or same thing at gmail), and I'd be happy to chat.  Thanks so much for making the time for my request.

Best,

Dave

**Comment by tejesh0** [comment]
@dwmmclaughlin villages_11 (Sikkim) can be found here. https://github.com/datameet/indian_village_boundaries/tree/master/sk
