### ISSUE TITLE
Licensing Enquiry

### ISSUE THREAD

**Issue by BrendonEdwards** [justinelliotmeyers/official_india_2011_village_boundary_polygons#3]
Hi Thanks for this file it is extremely useful as I'm looking at matching these to census counts to map the population. 

One question I had is this data released under an Open Licence? I will be using it at work and would like to avoid using any data that is government data that I am not authorised to have access to. I have tried to contact several govt. bodies to get the same data but have been knocked back on all occasions.

**Comment by justinelliotmeyers** [comment]
reach out to governments for license response. I get the same one you do.
