### ISSUE TITLE
Jharkhand Part2 rar not being extracted

### ISSUE THREAD

**Issue by tejendrapsingh** [justinelliotmeyers/official_india_2011_village_boundary_polygons#4]
.shp located at https://github.com/justinelliotmeyers/official_india_2011_village_boundary_polygons/blob/master/villages_20.shp.part2.rar
is not extracting. 

Part 1 does not plot the entire state.
Please have a look into it.

**Comment by justinelliotmeyers** [comment]
everything downloads/ extracts correctly
