### ISSUE TITLE
Assam village boundaries

### ISSUE THREAD

**Issue by srashmitapatro** [justinelliotmeyers/official_india_2011_village_boundary_polygons#5]
Any possible way to get Assam village boundaries?

Thanks.

**Comment by justinelliotmeyers** [comment]
will upload data as available

**Comment by KamleshSharmaESRI** [comment]
Hi Justine- May I have your email ID please? Need to discuss about data uses and Source.

**Comment by justinelliotmeyers** [comment]
@KamleshSharmaESRI please open a new issue with any questions or concerns.
Thanks!
Justin
