### ISSUE TITLE
Official official_india_2011_village_boundary_polygons

### ISSUE THREAD

**Issue by JimBillyGraham** [justinelliotmeyers/official_india_2011_village_boundary_polygons#6]
Justin,

I am missionary serving in a private evangelical missions,
After a long struggle i could download the data files and its working.
Is there is any possible to combine all the attributes statewise .
and do you have ward boundary with respective ward boundary 
 Jim Billy Graham GM

**Comment by justinelliotmeyers** [comment]
What do you mean by combine attributes statewise? Do you only want state boundaries?

What city wards do you need?

Thanks!
Justin

**Comment by JimBillyGraham** [comment]
Dear justin ,
 Thank you for your reply.


I am attaching a  document
Kindly find it below

  In His service...

*  B*ro.Jim Billy Graham
 Personal: +917295860051

**Comment by JimBillyGraham** [comment]
Dear justin,
can you get me what i mean




  In His service...

*  B*ro.Jim Billy Graham
 Personal: +917295860051

**Comment by justinelliotmeyers** [comment]
Sorry, no documents came through. Please explain in issue, no attachment needed. Copy and paste text if possible. Thanks!
Justin

**Comment by JimBillyGraham** [comment]
Dear Justin,
[image: image.png]
*Figure 1        which shows all the combined data.*

[image: image.png]
*Figure **2**  Shows the Attribute table opened for Villages 10*


[image: image.png]

*Figure **3* *shows the attribute table for villages 10*

In the above figures I have mentioned it

The need is:

I want the villages with the respective state District and sub district.

As like the village boundary I need ward boundary with respective
town/cities with district state.

So that it will be easy for me to plot our locations and to identify it
easily
* And also the villages of Bihar in Four** different dataset [
**missing_name_BIHAR, villages_0_SpatialJoin2, villages_01
]*
 Can i get this combined in single dataset or state wise

In His service...

*  B*ro.Jim Billy Graham
 Personal: +917295860051

**Comment by JimBillyGraham** [comment]
Dear Justin

The need is:

I want the villages with the respective state District and sub district.

As like the village boundary I need ward boundary with respective
town/cities with district state.

So that it will be easy for me to plot our locations and to identify it
easily
* And also the villages of Bihar in Four** different dataset [
**missing_name_BIHAR, villages_0_SpatialJoin2, villages_01
]*
 Can i get this combined in single dataset or state wise




  In His service...

*  B*ro.Jim Billy Graham
 Personal: +917295860051

**Comment by justinelliotmeyers** [comment]
There are other datasets that should allow you to do this. I'm sorry, I don't think I can help or this repo has an issue to provide subset datasets for individual code. You can always fork and derive a new dataset for your needs.

**Comment by JimBillyGraham** [comment]
[Git hub village boundaries.docx](https://github.com/justinelliotmeyers/official_india_2011_village_boundary_polygons/files/3052547/Git.hub.village.boundaries.docx)

**Comment by JimBillyGraham** [comment]
what is fork ?
Help me

**Comment by justinelliotmeyers** [comment]
https://help.github.com/en/articles/fork-a-repo

**Comment by justinelliotmeyers** [comment]
The dataset needs work, updates, and cleaning. I provide raw official data, and people develop things on top of it - Explore geoprocessing tools - you should be able to figure it out pretty easily! dissolve based on code and name - i think the solution is right in front of you ;)

**Comment by JimBillyGraham** [comment]
Dear Justin,

Thank you for your response. I am new to this and couldn't follow your steps.
i need your assistance

**Comment by JimBillyGraham** [comment]
can you provide the village census codes document

**Comment by justinelliotmeyers** [comment]
You will find any associated documents on the census website. Good luck!

**Comment by justinelliotmeyers** [comment]
If you only have a hand full of locations per tehsil, you could color code vs plot. Or plot as point instead of looking at a village poly dataset.

**Comment by JimBillyGraham** [comment]
sorry 
 i meant that,
The census codes according the to the villages mapped

**Comment by JimBillyGraham** [comment]
Do you have Sub District boundary for India according to census 2011

**Comment by JimBillyGraham** [comment]
can you link with me to the dataset
